# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd5c5f281b6fc69099eac6bd2b30ec105cf7d130e89a9cc87322349c0df80112d17bbf03d59daed0db5bbca8fc422417b5171c546537d994ca090e7bdac59ee7

test:
  secret_key_base: 22d12d64eb7f3bd0996d331cc398c838cff1f66157df0b64186fbfbb7c456c8637d2bb12db3658e49e179eef537d27813c7a94b04ab1c252eb38cbaf6c43a2b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
